# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expId', models.CharField(max_length=200)),
                ('repId', models.CharField(max_length=200)),
                ('N', models.IntegerField()),
                ('nPhi', models.IntegerField()),
                ('dt', models.FloatField()),
                ('v0', models.FloatField()),
                ('drag', models.FloatField()),
                ('Vuu', models.FloatField()),
                ('Vpp', models.FloatField()),
                ('Vzz', models.FloatField()),
                ('Vu', models.FloatField()),
                ('Vp', models.FloatField()),
                ('Vz', models.FloatField()),
                ('dVu', models.FloatField()),
                ('dVp', models.FloatField()),
                ('dVz', models.FloatField()),
                ('youtube', models.CharField(max_length=200)),
                ('flickr', models.CharField(max_length=200)),
            ],
        ),
    ]
