# Generated by Django 5.0 on 2023-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repId', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('simId', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('experiment', models.CharField(max_length=200)),
                ('engine', models.CharField(max_length=200)),
                ('dim', models.IntegerField()),
                ('N', models.IntegerField()),
                ('nPhi', models.IntegerField()),
                ('tMax', models.FloatField()),
                ('dt', models.FloatField()),
                ('u0', models.FloatField()),
                ('drag', models.FloatField()),
                ('a0', models.FloatField()),
                ('a00', models.FloatField()),
                ('a1', models.FloatField()),
                ('b0', models.FloatField()),
                ('b00', models.FloatField()),
                ('b1', models.FloatField()),
                ('c0', models.FloatField()),
                ('c00', models.FloatField()),
                ('c1', models.FloatField()),
                ('sx', models.FloatField()),
                ('sy', models.FloatField()),
                ('sz', models.FloatField()),
                ('mode', models.IntegerField()),
                ('parameters', models.CharField(max_length=200)),
            ],
        ),
    ]
