# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malkoDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiments',
            name='N',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='Vp',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='Vpp',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='Vu',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='Vuu',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='Vz',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='Vzz',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='dVp',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='dVu',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='dVz',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='drag',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='flickr',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='nPhi',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='repId',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='v0',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='youtube',
        ),
    ]
